services:
  app:
    build: .
    container_name: tenpo-app
    depends_on:
      - db
      - redis
    networks:
      - tenpo_default
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: tenpo.123
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379

  db:
    image: postgres:15
    container_name: tenpo-db
    networks:
          tenpo_default:
            ipv4_address: 172.19.0.2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: tenpo.123
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      retries: 5
      start_period: 10s
    restart: always


  redis:
    image: redis:latest
    container_name: tenpo-redis
    networks:
          tenpo_default:
            ipv4_address: 172.19.0.3
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      retries: 5
      start_period: 10s
    restart: always


networks:
  tenpo_default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/16
